Solved tasks module 1
js-tasks-ru/jsbasic-20230911_klaster26 pull request #3
Opened 2023-09-16 20:09 UTC by nickitey

### Task 1
The function returns factorial of input _number_. [^1] 
[^1]: Fixed. First solution user a recursion which does not response to the task condition.

### Task 2
The function accepts _string_ then returns true if it is

- not _null_;
- not equal to empty _string_;
- longer than 4 chars;
- not containing _spaces_.

### Task 3
The function accepts _string_, then returns the same _string_ but with the first char transformed to upper case. If the _string_ is empty it returns the empty _string_.

### Task 4
The function accepts _string_, returns true if it contains keywords '_1xBet_' and '_XXX_' [^2]. 
[^2] Does not depend on registry.

### Task 5
The function accepts _string_ and _number_ and then returns concatenated _string_, which consists of _substring_ equals to accepted _string's_ chars in amount of accepted _number_, and _substring_ '....

2023-09-16 20:10 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-09-18 09:39 UTC, SinimaWath requested changes

2023-09-18 09:39 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  } return false;
давай упростим без if: `return str.toLowerCase().includes('1xBet'.toLowerCase()) || str.toLowerCase().includes('XXX'.toLowerCase())`

2023-09-18 09:39 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  } return true;
Тут тоже давай попробуем решить без if `return ...`.

Также если проверишь то `name == null || name == ""`, можно сократить до `!name`

2023-09-18 16:38 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-09-18 16:38 UTC, nickitey commented on 1-module/4-task/index.js
> +  } return false;
Исправил. Смысл понял: если простым языком, мы утверждаем, что строка на входе включает наши кодовые слова, требуем возвратить, истина это или ложь. Если строка действительно их включает, то истина, соответственно, наоборот.

2023-09-18 17:11 UTC, nickitey commented on 1-module/2-task/index.js
> +  } return true;
Понял. Null и пустая строка - falsy значения, при переводе их в boolean функция вернет false. В остальном решение аналогично задаче #4.

2023-09-18 17:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-09-20 12:59 UTC, SinimaWath approved these changes

2023-09-20 13:00 UTC, merged